pipeline {
	agent any
	
	stages{
	
		stage('Compilation Stage'){
			steps{
				bat 'mvn clean compile'
				
			}
		}
		
		stage('Testing Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
					sh 'mvn test'
				}
			}
		}
		
		stage('Deployment Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
					sh 'mvn deploy'
				}
			}
		}
	}
}